# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-12 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('author_text', models.TextField(blank=True, default='')),
                ('publication', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.SmallIntegerField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, default='')),
                ('web_link', models.CharField(blank=True, default='', max_length=500)),
                ('last_viewed', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('uploaded', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents')),
                ('linked_document_text', models.TextField(blank=True, default='')),
                ('authors', models.ManyToManyField(blank=True, to='hypothesize_app.Author')),
                ('linked_documents', models.ManyToManyField(blank=True, to='hypothesize_app.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='')),
                ('last_viewed', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('documents', models.ManyToManyField(blank=True, to='hypothesize_app.Document')),
                ('topics', models.ManyToManyField(blank=True, to='hypothesize_app.Topic')),
            ],
        ),
    ]
